Zooper Assignment

In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as dt

Dataset Creation

In [32]:
def create_dataset(set_path):
    n=1000000
    customer_id = np.arange(1, n+1)
    vehicle_id = np.arange(1, n+1)
    tenure = np.random.choice([1,2,3,4],size=n, p=[0.2,0.3,0.4,0.1])
    vehicle_value = np.full(n,100000)
    premium = tenure * 100
    dates = pd.date_range("2024-01-01","2024-12-31")
    purchase_dates = np.random.choice(dates, n)
    policy_start = purchase_dates + pd.Timedelta(days=365)
    policy_end = policy_start + pd.to_timedelta(tenure*365, unit="D")
    policy_df = pd.DataFrame({
    "Customer_ID": customer_id,
    "Vehicle_ID": vehicle_id,
    "Vehicle_Value": vehicle_value,
    "Premium": premium,
    "Policy_Purchase_Date": purchase_dates,
    "Policy_Start_Date": policy_start,
    "Policy_End_Date": policy_end,
    "Policy_Tenure": tenure
    })
    policy_df.to_csv(path_or_buf=set_path,index=False)
    return "All Set"

In [33]:
create_dataset("policy_dataset.csv")

'All Set'

In [34]:
policy_df=pd.read_csv('policy_dataset.csv')
policy_df.sample(20)

,Customer_ID,Vehicle_ID,Vehicle_Value,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date,Policy_Tenure
222295,222296,222296,100000,100,2024-10-22,2025-10-22,2026-10-22,1
816614,816615,816615,100000,100,2024-05-26,2025-05-26,2026-05-26,1
811167,811168,811168,100000,300,2024-03-10,2025-03-10,2028-03-09,3
627715,627716,627716,100000,200,2024-12-21,2025-12-21,2027-12-21,2
75745,75746,75746,100000,200,2024-04-12,2025-04-12,2027-04-12,2
793143,793144,793144,100000,300,2024-03-18,2025-03-18,2028-03-17,3
975282,975283,975283,100000,300,2024-01-01,2024-12-31,2027-12-31,3
42722,42723,42723,100000,400,2024-01-19,2025-01-18,2029-01-17,4
881768,881769,881769,100000,300,2024-09-07,2025-09-07,2028-09-06,3
210770,210771,210771,100000,300,2024-12-13,2025-12-13,2028-12-12,3
926815,926816,926816,100000,200,2024-03-02,2025-03-02,2027-03-02,2
373117,373118,373118,100000,100,2024-10-04,2025-10-04,2026-10-04,1
148414,148415,148415,100000,200,2024-09-10,2025-09-10,2027-09-10,2
808861,808862,808862,100000,200,2024-07-04,2025-07-04,2027-07-04,2
277389,277390,277390,100000,400,2024-01-15,2025-01-14,2029-01-13,4
765477,765478,765478,100000,200,2024-10-07,2025-10-07,2027-10-07,2
450531,450532,450532,100000,300,2024-03-28,2025-03-28,2028-03-27,3
878488,878489,878489,100000,100,2024-01-07,2025-01-06,2026-01-06,1
432264,432265,432265,100000,200,2024-12-01,2025-12-01,2027-12-01,2
175115,175116,175116,100000,200,2024-09-01,2025-09-01,2027-09-01,2

In [35]:
policy_df.shape

(1000000, 8)

Building Claim Dataset

In [36]:
policy_df['Policy_Purchase_Date'] = pd.to_datetime(policy_df['Policy_Purchase_Date'])
policy_df['purchase_day']=policy_df['Policy_Purchase_Date'].dt.day
eligible_df=policy_df[policy_df['purchase_day'].isin([7,14,21,28])]
eligible_df

,Customer_ID,Vehicle_ID,Vehicle_Value,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date,Policy_Tenure,purchase_day
3,4,4,100000,100,2024-02-14,2025-02-13,2026-02-13,1,14
11,12,12,100000,300,2024-06-21,2025-06-21,2028-06-20,3,21
13,14,14,100000,300,2024-08-14,2025-08-14,2028-08-13,3,14
21,22,22,100000,300,2024-03-07,2025-03-07,2028-03-06,3,7
24,25,25,100000,300,2024-06-21,2025-06-21,2028-06-20,3,21
...,...,...,...,...,...,...,...,...,...
999969,999970,999970,100000,100,2024-01-14,2025-01-13,2026-01-13,1,14
999983,999984,999984,100000,100,2024-06-21,2025-06-21,2026-06-21,1,21
999985,999986,999986,100000,300,2024-05-21,2025-05-21,2028-05-20,3,21
999988,999989,999989,100000,300,2024-08-14,2025-08-14,2028-08-13,3,14
999991,999992,999992,100000,300,2024-04-21,2025-04-21,2028-04-20,3,21

In [37]:
claims_2025 = eligible_df.sample(frac=0.30, random_state=42)

In [38]:
claims_2025_df = pd.DataFrame({
    "Customer_ID": claims_2025["Customer_ID"],
    "Vehicle_ID": claims_2025["Vehicle_ID"],
    "Claim_Amount": 10000,
    "Claim_Date": claims_2025["Policy_Start_Date"],
    "Claim_Type": 1
})

In [39]:
four_year_policies = policy_df[
    policy_df["Policy_Tenure"] == 4
]

In [40]:
claims_2026 = four_year_policies.sample(frac=0.10, random_state=42)

In [41]:
four_year_policies = policy_df[
    policy_df["Policy_Tenure"] == 4
]

In [42]:
claims_2026 = four_year_policies.sample(frac=0.10, random_state=42)

In [43]:
dates_2026 = pd.date_range("2026-01-01","2026-02-28")

claim_dates = np.random.choice(dates_2026, len(claims_2026))

In [44]:
claims_2026_df = pd.DataFrame({
    "Customer_ID": claims_2026["Customer_ID"],
    "Vehicle_ID": claims_2026["Vehicle_ID"],
    "Claim_Amount": 10000,
    "Claim_Date": claim_dates,
    "Claim_Type": 2
})

In [45]:
claims_df = pd.concat([claims_2025_df, claims_2026_df])
claims_df.reset_index(drop=True, inplace=True)
claims_df["Claim_ID"] = np.arange(1, len(claims_df)+1)
claims_df = claims_df[
    ["Claim_ID","Customer_ID","Vehicle_ID",
     "Claim_Amount","Claim_Date","Claim_Type"]
]
claims_df.sample(5)

,Claim_ID,Customer_ID,Vehicle_ID,Claim_Amount,Claim_Date,Claim_Type
27171,27172,70091,70091,10000,2025-02-20,1
41873,41874,892084,892084,10000,2026-01-03 00:00:00,2
35005,35006,823159,823159,10000,2025-06-28,1
14573,14574,486810,486810,10000,2025-07-14,1
10575,10576,155077,155077,10000,2025-06-21,1

In [46]:
policy_df.head()

,Customer_ID,Vehicle_ID,Vehicle_Value,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date,Policy_Tenure,purchase_day
0,1,1,100000,400,2024-02-13,2025-02-12,2029-02-11,4,13
1,2,2,100000,400,2024-07-11,2025-07-11,2029-07-10,4,11
2,3,3,100000,300,2024-01-23,2025-01-22,2028-01-22,3,23
3,4,4,100000,100,2024-02-14,2025-02-13,2026-02-13,1,14
4,5,5,100000,300,2024-04-11,2025-04-11,2028-04-10,3,11

Analysis & Quering

In [47]:
policy_df['Purchase_Year']=policy_df['Policy_Purchase_Date'].dt.year
policy_df_2024=policy_df[policy_df['Purchase_Year']==2024]
total_premium_2024=policy_df_2024['Premium'].sum()
total_premium_2024

239989700

In [48]:
claims_df['Claim_Date']=pd.to_datetime(claims_df['Claim_Date'])
claims_df['Year']=claims_df['Claim_Date'].dt.year
claims_df['Month']=claims_df['Claim_Date'].dt.month

In [53]:
claimed = claims_df['Vehicle_ID'].unique()

In [49]:
claims_summary = claims_df.groupby(['Year','Month'])['Claim_Amount'].sum().reset_index()
claims_summary

    Year  Month  Claim_Amount
0   2025      1      32230000
1   2025      2      32580000
2   2025      3      32830000
3   2025      4      33410000
4   2025      5      31780000
5   2025      6      33220000
6   2025      7      33410000
7   2025      8      32510000
8   2025      9      32900000
9   2025     10      32970000
10  2025     11      32780000
11  2025     12      32430000
12  2026      1      52010000
13  2026      2      47730000

In [50]:
merge_df = pd.merge(policy_df, claims_df, on='Customer_ID')
merge_df

,Customer_ID,Vehicle_ID_x,Vehicle_Value,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date,Policy_Tenure,purchase_day,Purchase_Year,Claim_ID,Vehicle_ID_y,Claim_Amount,Claim_Date,Claim_Type,Year,Month
0,4,4,100000,100,2024-02-14,2025-02-13,2026-02-13,1,14,2024,5321,4,10000,2025-02-13,1,2025,2
1,22,22,100000,300,2024-03-07,2025-03-07,2028-03-06,3,7,2024,27599,22,10000,2025-03-07,1,2025,3
2,25,25,100000,300,2024-06-21,2025-06-21,2028-06-20,3,21,2024,17000,25,10000,2025-06-21,1,2025,6
3,147,147,100000,300,2024-07-21,2025-07-21,2028-07-20,3,21,2024,28632,147,10000,2025-07-21,1,2025,7
4,153,153,100000,300,2024-02-14,2025-02-13,2028-02-13,3,14,2024,36172,153,10000,2025-02-13,1,2025,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49274,999896,999896,100000,200,2024-05-07,2025-05-07,2027-05-07,2,7,2024,27222,999896,10000,2025-05-07,1,2025,5
49275,999948,999948,100000,400,2024-03-20,2025-03-20,2029-03-19,4,20,2024,40474,999948,10000,2026-01-21,2,2026,1
49276,999953,999953,100000,400,2024-02-02,2025-02-01,2029-01-31,4,2,2024,42046,999953,10000,2026-02-17,2,2026,2
49277,999972,999972,100000,400,2024-03-10,2025-03-10,2029-03-09,4,10,2024,42906,999972,10000,2026-02-17,2,2026,2
49278,999989,999989,100000,300,2024-08-14,2025-08-14,2028-08-13,3,14,2024,25314,999989,10000,2025-08-14,1,2025,8

In [52]:
sale_month_ratio = merge_df.groupby('Month').agg({
    'Claim_Amount':'sum',
    'Premium':'sum'
})

sale_month_ratio['Ratio'] = sale_month_ratio['Claim_Amount'] / sale_month_ratio['Premium']

sale_month_ratio

       Claim_Amount  Premium      Ratio
Month
1          84240000  2848500  29.573460
2          80310000  2689300  29.862790
3          32830000   789500  41.583281
4          33410000   802900  41.611658
5          31780000   761900  41.711511
6          33220000   800200  41.514621
7          33410000   796600  41.940748
8          32510000   779600  41.700872
9          32900000   785000  41.910828
10         32970000   797500  41.341693
11         32780000   781000  41.971831
12         32430000   782200  41.459985

In [ ]:
merge_df.groupby('Policy_Tenure')['ratio'].mean()

Policy_Tenure
1    100.000000
2     50.000000
3     33.333333
4     25.000000
Name: ratio, dtype: float64

In [ ]:
tenure_ratio = merge_df.groupby('Policy_Tenure').agg({
    'Claim_Amount':'sum',
    'Premium':'sum'
})
tenure_ratio['Claim_Premium_Ratio'] = tenure_ratio['Claim_Amount'] / tenure_ratio['Premium']
tenure_ratio

               Claim_Amount  Premium  Claim_Premium_Ratio
Policy_Tenure
1                  79680000   796800           100.000000
2                 118520000  2370400            50.000000
3                 157430000  4722900            33.333333
4                 138540000  5541600            25.000000

In [54]:
remaining = policy_df[~policy_df['Vehicle_ID'].isin(claimed)]

In [55]:
potential_liability = len(remaining) * 10000
potential_liability

9511020000

In [56]:
policy_df['Policy_Start_Date']=pd.to_datetime(policy_df['Policy_Start_Date'])
policy_df['Policy_End_Date']=pd.to_datetime(policy_df['Policy_End_Date'])

In [57]:
policy_df['Tenure_Days'] = (policy_df['Policy_End_Date'] - policy_df['Policy_Start_Date']).dt.days

In [58]:
policy_df['Daily_Premium'] = policy_df['Premium'] / policy_df['Tenure_Days']

In [59]:
cutoff = pd.to_datetime("2026-02-28")

In [ ]:
policy_df['Earned_Days'] = (
    policy_df.apply(lambda row: min(row['Policy_End_Date'], cutoff), axis=1) 
    - policy_df['Policy_Start_Date']
).dt.days.clip(lower=0)

KeyError: 0

In [61]:
policy_df['Earned_Premium'] = policy_df['Earned_Days'] * policy_df['Daily_Premium']

earned_premium = policy_df['Earned_Premium'].sum()
earned_premium

KeyError: 'Earned_Days'